#!/usr/bin/env bash
#Dispaly information about subdomains.
domain_information () {
    #Perform DNS lookup for the subdomain under specified domain
    line=$(dig "$2" "$1" | grep -Al 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    #Extract relevant information and print
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

#Check number of arguements passed to script
if [ "$#" == 1 ]
then
    # If there is only one arguement,
    # then call domain information function with predefined subdomain names
    domain_information "$1" "www"
    domain_information "$1" "web-02"
    domain_information "$1" "web-01"
    domain_information "$1" "lb-01"
elif [ "$#" == 2 ]
then
    # If there two arguments, call domain_information \
    # function with provided subdomain name
    domain_information "$1" "$2"
fi
