#!/usr/bin/env bash

# Check for correct number of arguments
if [ "$#" -ne 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign arguments variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# Disable strict host key checking for scp
export SCP="scp -o StrictHostKeyChecking=no -i $ssh_key_path"

# Transfer file to the server
$SCP "$file_path" "$username@$server_ip:~/"

if [ $? -eq 0 ]; then
  echo "File transfer successful"
else
  echo "File transfer failed"
fi
