#!/usr/bin/env bash
# Installs Nginx with following configurations:
#+    Listens on port 80.
#+    Returns page containing "Hello World!" when queried
#++    at root with a curl GET request.

#  updates package lists for available software packages.
apt-get update
# installs the Nginx web server.
apt-get install -y nginx

# Creates /etc/nginx/html directory, which will serve as document root directory for Nginx.
mkdir /etc/nginx/html
#  creates empty index.html file inside /etc/nginx/html directory.
touch /etc/nginx/html/index.html
#  sets the content of the index.html file to "Hello World!" using the echo command.
echo "Hello World!" > /etc/nginx/html/index.html
# Sets Nginx to listen port 80 and serve files from /etc/nginx/html directory.
printf %s "server {
     listen      80;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

# Restarts Nginx service to apply configuration changes.
service nginx restart
