#!/usr/bin/env bash

# Check if script is run as root
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

# Install Nginx if not already installed
if ! [ -x "$(command -v nginx)" ]; then
  apt-get update
  apt-get install -y nginx
fi

# Create custom Nginx configuration file for redirection
cat <<EOL > /etc/nginx/sites-available/redirect_me
server {
    listen 80;
    server_name itzenca.tech www.itzenca.tech;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=7YqlP7HYU1g/new_page;
    }

    # Include additional server blocks or configurations if needed
}

EOL

# Create symbolic link to enable site configuration
ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Remove default Nginx server block
rm /etc/nginx/sites-enabled/default

# Test Nginx configuration and reload Nginx
nginx -t
systemctl reload nginx
