#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#+     at the root with a curl GET request.
#+    Configures /redirect_me as a "301 Moved Permanently".
#+    Includes a custom 404 page containing "Ceci n'est pas une page".
#+    Contains a custom HTTP header named X-Served-By.
#+    The value of the HTTP header is the hostname of the running server.

apt-get install -y nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i '/server {/a \
    listen 80 default_server;\n    listen [::]:80 default_server;\n    add_header X-Served-By $HOSTNAME;\n    root   /var/www/html;\n    index  index.html index.htm;\n\n    location /redirect_me {\n        return 301 https://YouTube.com/;\n    }\n\n    error_page 404 /404.html;\n    location /404 {\n        root /var/www/html;\n        internal;\n    }\n' /etc/nginx/sites-available/default
service nginx restart
