#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

sudo  apt-get -y update
sudo apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    user haproxy
    group haproxy
    maxconn 2000
frontend itzenca.tech
    timeout client  30000
    bind 0:80
    default_backend itzenca.tech_backend

backend itzenca.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 255935-web-01 18.233.62.201:80 check
    server 255935-web-02 100.26.164.127:80 check

" >> /etc/haproxy/haproxy.cfg 

sudo service haproxy restart
