#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

sudo apt-get -y update
sudo apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    user haproxy
    group haproxy
    maxconn 2000
defaults
    mode http
    timeout connect 5s
    timeout client 50s
    timeout server 50s
frontend nginx_webservers
    bind 0:80
    default_backend nginx_webservers_backend

backend nginx_webservers_backend
    balance roundrobin
    server 255935-web-01 18.233.62.201:80 check
    server 255935-web-02 100.26.164.127:80 check
    http-response set-header X-Served-By 03-web-01

" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
