#!/usr/bin/env bash
sudo rm /etc/nginx/sites-enabled/default
# Create a symbolic link to the default Nginx configuration for port 80
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart the Nginx service to apply the configuration changes
sudo service nginx restart
