#!/usr/bin/env bash
# Script configures Nginx to listen on port 80.
apt-get -y update
apt-get -y install nginx
sed -i 's/80 default_server;/80;/g' /etc/nginx/sites-available/default
service nginx start
