#!/usr/bin/env bash
# Script runs the 'whoami' command under user passed as an argument.

# Check if exactly one argument is provided
if [ $# -ne 1 ]; then
  echo "Usage: $0 <username>"
  exit 1
fi

# Run 'whoami' as specified user
sudo -u "$1" whoami
