#!/usr/bin/env bash
# Script fixes Nginx to run as nginx user and listen on port 8080

sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
sudo service nginx restart
